# Generated by Django 3.2.4 on 2021-07-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='allImages')),
                ('desc', models.CharField(default='', max_length=1000)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
