# Generated by Django 3.2.5 on 2021-07-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.CharField(default='Bal Apate', max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='imageName',
            field=models.CharField(default='Bal Apate', max_length=100),
        ),
    ]
