# Generated by Django 3.2.5 on 2021-07-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210703_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='desc',
            field=models.CharField(default='Bal Apate', max_length=1000),
        ),
    ]
