# Generated by Django 3.2.5 on 2021-07-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('websiteName', models.CharField(default='', max_length=10000)),
                ('websiteLink', models.CharField(default='', max_length=10000)),
            ],
        ),
    ]
